PROJECT:=VSP

include makefile-latex/latex-std-dependence.mk

DEPS_MAIN_TEX:=$(wildcard vsp-beamer/*.cls) $(wildcard vsp-beamer/*.sty) $(wildcard vsp-beamer/assets/*.png)

include makefile-latex/makefile-latex.mk
